### ISSUE TITLE
Contact request 

### ISSUE THREAD

**Issue by daviddean-x** [NepuShiro/RedirectLog#1]
Dear @NepuShiro 
Sorry for posting here and it's not related to this repo, 
I had seen you have reworked raweb and like to request if you could enable issues tab there.

Reason 
Newer clients need ntlm authentication against the server and some adjustments to make newer remote desktop clients working against raweb.
Best regards

**Comment by NepuShiro** [comment]
@thefiredragon 
I've opened issues on the raweb repo, so if you could move that issue there.
but keep in mind I reworked/ported raweb to nodejs just as a small hobby project and didn't really need any auth or anything of that sort, by all means you're free to make a pr and add it yourself.
